name: Push directory to another repository
'on': push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: AzurePAT
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        shell: pwsh
        run: powershell.exe .\git.ps1
